---
- name: "Installing docker plugin"
  copy:
    src: docker.py
    dest: "{{ zabbix_agent_script_path }}/docker.py"
    owner: root
    group: root
    mode: 0755
  become: yes

- name: "Installing docker plugin config"
  template:
    src: docker.conf.j2
    dest: "{{ zabbix_agent_include }}/docker.conf"
    owner: root
    group: zabbix
    mode: 0755
  notify: restart zabbix-agent
  become: yes

- name: "Getting list of user groups"
  shell: "awk -F: '{print $1}' /etc/group"
  register: system_groups
  tags:
    - skip_ansible_lint

- name: "Checking docker prerequisites"
  fail:
    msg: "Can't continue without docker group present"
  when: '"zabbix" not in system_groups.stdout_lines'

- name: Adding zabbix to group docker
  user:
    name: zabbix
    groups: docker
    append: yes
  become: yes
