---
- name: "Installing nginx checker"
  copy:
    src: nginx-stat.py
    dest: "{{ zabbix_agent_script_path }}/nginx-stat.py"
    owner: root
    group: root
    mode: 0755
  become: yes

- name: "Installing nginx plugin config"
  template:
    src: nginx.conf.j2
    dest: "{{ zabbix_agent_include }}/nginx.conf"
    owner: root
    group: zabbix
    mode: 0755
  notify: restart zabbix-agent
  become: yes
