---

- name: "Installing postgresql config"
  template:
    src: postgresql.conf.j2
    dest: "{{ zabbix_agent_include }}/postgresql.conf"
    owner: root
    group: zabbix
    mode: 0755
  notify: restart zabbix-agent
  become: yes
