---
# Tasks specific for RedHat systems

- name: "RedHat | Use EPEL package name"
  set_fact:
    zabbix_agent_package: "zabbix{{ zabbix_short_version }}-agent"
  when:
    - zabbix_repo == "epel"
  tags:
    - zabbix-agent
    - init

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  register: yum_repo_installed
  become: yes
  when:
    zabbix_repo == "zabbix"
  tags:
    - zabbix-agent

- name: "Do a yum clean"
  shell: yum clean all
  when: yum_repo_installed.changed
  become: yes
  tags:
    - skip_ansible_lint

- name: "RedHat | Installing zabbix-agent"
  package:
    pkg: "{{ item }}"
    state: "{{ zabbix_agent_package_state }}"
  become: yes
  with_items: "{{ zabbix_agent_packages }}"
  tags:
    - init
    - zabbix-agent

- name: "Install policycoreutils-python"
  yum:
    name: policycoreutils-python
    state: present
  when: zabbix_selinux
  become: yes
  tags:
    - init
    - zabbix-agent

- name: "Installing libvirt dependencies"
  package:
    pkg: libvirt-python
    state: present
  become: yes
  when:
    - zabbix_agent_libvirt

- name: "RedHat | Enable the service"
  service:
    name: "{{ zabbix_agent_service }}"
    enabled: yes
    use: service
  become: yes
  tags:
    - zabbix-agent
    - init
    - service
